# إعدادات الاتصال بقاعدة بيانات MySQL الحقيقية
spring.datasource.url=jdbc:mysql://localhost:3306/upm_events?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# ضعي هنا اسم المستخدم وكلمة المرور الخاصة ببرنامج MySQL Workbench لديكِ
spring.datasource.username=root
spring.datasource.password=123456789
# تحديث الجداول تلقائياً دون مسح البيانات الحقيقية
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# إظهار استعلامات SQL في الـ Console للتأكد من عملها (اختياري)
spring.jpa.show-sql=true