-- =========================================================================
-- 1. DROP TABLES
-
-- 2. CREATE TABLE: USERS
-- =========================================================================
CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR2(100) NOT NULL,
                       email VARCHAR2(100) UNIQUE NOT NULL,
                       password VARCHAR2(255) NOT NULL,
                       role VARCHAR2(20) DEFAULT 'student',
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT chk_upm_email CHECK (email LIKE '%@student.upm.edu.my')
);

-- =========================================================================
-- 3. CREATE TABLE: INTERESTS
-- =========================================================================
CREATE TABLE interests (
                           interest_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           interest_name VARCHAR2(100) UNIQUE NOT NULL
);

-- =========================================================================
-- 4. CREATE TABLE: USER_INTERESTS
-- =========================================================================
CREATE TABLE user_interests (
                                user_id NUMBER NOT NULL,
                                interest_id NUMBER NOT NULL,
                                PRIMARY KEY (user_id, interest_id),
                                CONSTRAINT fk_ui_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                                CONSTRAINT fk_ui_interest FOREIGN KEY (interest_id) REFERENCES interests (interest_id) ON DELETE CASCADE
);

-- =========================================================================
-- 5. CREATE TABLE: EVENT_RECORDS
-- =========================================================================
CREATE TABLE event_records (
                               event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id NUMBER NOT NULL,
                               interest_id NUMBER,
                               event_title VARCHAR2(150) NOT NULL,
                               event_description CLOB,
                               event_date DATE NOT NULL,
                               event_time VARCHAR2(20) NOT NULL,
                               venue VARCHAR2(150),
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_event_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                               CONSTRAINT fk_event_interest FOREIGN KEY (interest_id) REFERENCES interests (interest_id) ON DELETE SET NULL
);

-- =========================================================================
-- 6. INSERT INITIAL DATA
-- =========================================================================

INSERT INTO interests (interest_name) VALUES ('Programming & IT');
INSERT INTO interests (interest_name) VALUES ('Sports & Fitness');
INSERT INTO interests (interest_name) VALUES ('Art & Design');
INSERT INTO interests (interest_name) VALUES ('Workshops & Career');

INSERT INTO users (full_name, email, password, role)
VALUES ('UPM Admin Team', 'admin@student.upm.edu.my', 'admin123', 'admin');

INSERT INTO users (full_name, email, password, role)
VALUES ('Remas Khaled', 'remas@student.upm.edu.my', 'remas123', 'student');

INSERT INTO user_interests (user_id, interest_id) VALUES (2, 1);

INSERT INTO event_records (user_id, interest_id, event_title, event_description, event_date, event_time, venue)
VALUES (1, 1, 'Java Spring Boot & Oracle DB Workshop', 'Learn how to connect full-stack application using Spring boot framework.', TO_DATE('2026-06-15', 'YYYY-MM-DD'), '10:00 AM', 'CCSE Lab 4');

COMMIT;